import type { Metadata } from 'next';
import PacketDataClient from './_components/PacketDataClient';

export const metadata: Metadata = {
  title: 'Minecraft Packet Data',
  description: 'Browse and compare Minecraft packet definitions across versions.',
};

export default function PacketDataPage() {
  return (
    <main className="min-h-screen">
      <div className="container py-6 md:py-8">
        <h1 className="mb-2 text-2xl font-bold text-text md:text-3xl">
          Minecraft Packet Data
        </h1>
        <p className="mb-6 text-sm text-text-dim">
          ⚠️ Autogenerated from the vanilla server — some definitions, especially field names,
          are most certainly wrong. Hover a wire type such as <span className="font-mono">VarInt</span> or{' '}
          <span className="font-mono">List</span> to see how it is read.
        </p>
        <PacketDataClient />
      </div>
    </main>
  );
}
